# Generated by Django 3.2 on 2021-04-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('ProjectType', models.CharField(max_length=30)),
                ('Client', models.CharField(max_length=30)),
                ('Technology', models.CharField(max_length=30)),
                ('GithubLink', models.CharField(max_length=30)),
                ('Thumbnail', models.ImageField(upload_to='images/')),
                ('YoutubeLink', models.CharField(max_length=50)),
            ],
        ),
    ]
