# Generated by Django 3.2 on 2021-04-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='GithubLink',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='YoutubeLink',
            field=models.CharField(max_length=150),
        ),
    ]
