# Generated by Django 3.2 on 2021-04-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_project_youtubelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='YoutubeLink',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='GithubLink',
            field=models.CharField(max_length=150),
        ),
    ]
