# Generated by Django 3.2 on 2021-05-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=150)),
                ('BlogLink', models.CharField(blank=True, max_length=150)),
                ('Thumbnail', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
