# Generated by Django 3.2 on 2021-05-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Description',
            field=models.CharField(max_length=500),
        ),
    ]
